### ISSUE TITLE
Project Needs Package Reorganization

### ISSUE THREAD

**Issue by AnUnknownMiner** [Turkey2349/Call_Of_Minecraft-Zombies#8]
There just two main issues that I think should be fixed.

- [ ] The plugin configuration files don't have their own separate folder.

This can be fixed by moving them into a new folder called "resources" or whatever at the base of the src.

- [ ] The project uses improper package declarations. Usually, you only use `.com` if you own a website with that top level domain, but since (afaik) you don't the package should be named to `me.Turkey2349.zombies`

Please correct me if I'm wrong about the second one.

**Comment by Turkey2349** [comment]
what do you mean the config files don't have their own folder?
also as for the package name, yes your way works to, but it is not that major of an issue and there is no reason for me to change them now.

**Comment by gdude2002** [comment]
@AnUnknownMiner is correct - you shouldn't do this. It's quite important as someone that may end up owning that domain (which is entirely possible) may then use it in their package declarations, causing a conflict with anything you may have written here.

Since you're using GitHub, however, the recommendation is `com.github.Turkey2349.zombies` - You could alternatively use your email address, `com.<gmail, hotmail, etc>.Turkey2349`, or whatever it is you use, but the former seems better.

---

Additionally, by convention, your project should be laid out as follows.

```
- src/
+ - main/
| + - java/ (Main plugin code)
| + - resources/ (Non-code files to be included in the JAR, eg .yml files)
+ - test/
| + - java/ (Unit test code)
| + - resources/ (Non-code files related to unit tests)
```
